const list = {
  metodos: [
    { id: 1, nome: "Teste de Usabilidade", descricao: "Esta técnica consiste em realizar uma simulação e observar a interação do usuário com o sistema em um campo ou laboratório." },
    { id: 2, nome: "Avaliação heurística", descricao: "Este método consiste em avaliar o sistema de acordo com os conhecimentos ergonômicos, padrões de usabilidade e heurísticas desenvolvidos por especialista." },
    { id: 3, nome: "Lista de verificação", descricao: "Este método consiste em encontrar problemas de usabilidade nas interfaces a partir de lista de verificações, guidelines e normas prontas." },
    { id: 4, nome: "Percurso Cognitivo", descricao: "Este método consiste em verificar os processos cognitivos dos usuários iniciantes através de lista de verificação orientada a tarefa." },
    { id: 5, nome: "Survey", descricao: "Este método tem por objetivo avaliar a satisfação do usuário em relação ao sistema" },
    { id: 6, nome: "Questionário", descricao: "Este método tem por objetivo avaliar a satisfação do usuário em relação ao sistema" },
  ],
  metricas: [
    { id: 1, nome: "facilidade de navegação", metodos: [1, 2, 4, 5, 6] },
    { id: 2, nome: "numero de formas que o sistema fornece o status do sistema para o usuario", metodos: [3] },
    { id: 3, nome: "numero de erros do usuario", metodos: [3, 4] },
    { id: 4, nome: "Tempo médio de animaçao por página", metodos: [1, 2] },
    { id: 5, nome: "Média da frequência de som utilizado no sistema", metodos: [2, 4] },
    { id: 6, nome: "facilidade de uso", metodos: [1, 2, 4, 5, 6] },
    { id: 7, nome: "clareza das mensagens de erros apresentados pelo sistema", metodos: [1, 2] },
    { id: 8, nome: "Número de usuários que apresentam dúvidas quando diferentes palavras, situações ou ações significam a mesma coisa", metodos: [1, 2, 4, 5] },
    { id: 9, nome: "Facilidade de encontrar instruções de ajuda", metodos: [1, 5, 6] },
    { id: 10, nome: "Qualidade da informação disponibilizada pelo sistema", metodos: [5, 6] },
    { id: 11, nome: "Número de regiões distintas definidas para uma interface", metodos: [1, 5] },
    { id: 12, nome: "Número médio de itens distintos que o usuário deve examinar antes de tomar uma decisão de navegação ou de entrada de dados", metodos: [1, 2, 6] },
    { id: 13, nome: "Número de operações que podem ser desfeitas", metodos: [1, 2, 3] },
    { id: 14, nome: "Legibilidade do tamanho e tipo da fonte", metodos: [1, 2, 5, 6] },
    { id: 15, nome: "Número de usuários que está confortável com o design e a metodologia usada no sistema", metodos: [1, 5] },
    { id: 16, nome: "Número médio de toques necessários para uma função específica", metodos: [1, 2] },
    { id: 17, nome: "Número de formas que o sistema ajuda os usuários a conhecer as suas posições e situações no site para decidir as suas ações para ir para próximas páginas", metodos: [1,	2] },
    { id: 18, nome: "Número de interações que possuem restrição de tempo", metodos: [1, 2, 3] },
    { id: 19, nome: "Nível médio de satisfação do usuário", metodos: [5, 6] },
    { id: 20, nome: "Número de mensagens de interface com problema", metodos: [1, 2, 3, 5] },
    { id: 21, nome: "Facilidade de alternar entre a ajuda e atividade realizada no sistema", metodos: [1, 2, 6] },
    { id: 22, nome: "Habilidade do usuário de compreender a estrutura e as funções", metodos: [1, 2] },
    { id: 23, nome: "Tempo médio (em segundos) que o usuário gasta para selecionar a ação apropriada para uma tarefa", metodos: [1, 2] },
    { id: 24, nome: "Número de opções que o sistema fornece para controlar e configurar os elementos da página", metodos: [1, 2, 3] },
    { id: 25, nome: "Número médio de links que podem ser selecionados por página", metodos: [1, 2, 3] },
    { id: 26, nome: "Número de páginas que possuem opção de voltar", metodos: [1, 2, 3,	4] },
    { id: 27, nome: "Habilidade do usuário para realizar as suas ações", metodos: [1, 4] },
    { id: 28, nome: "Número de feedbacks negativo dos usuários", metodos: [1, 5, 6] },
    { id: 29, nome: "Número de opções que o sistema disponibiliza para que opções importantes sejam altamente visíveis", metodos: [1, 2, 3, 5, 6] },
    { id: 30, nome: "Número de tentativas para realizar a correção de informações submetidas", metodos: [1, 3, 4] },

  ],
  requisitos: [
    { id: 1, nome: "O sistema não deve utilizar rolagem na tela inicial de aplicativos", metricas: [1, 12] },
    { id: 2, nome: "O sistema deve manter a estrutura de navegação estreita, simples e direta", metricas: [1, 12] },
    { id: 3, nome: "O sistema deve  utilizar navegação passo a passo consistente e explícita", metricas: [1, 6] },
    { id: 4, nome: "O sistema deve possuir atalhos para executar as funções", metricas: [1, 16] },
    { id: 5, nome: "O sistema deve possuir indicadores de localização nas rolagens de tela", metricas: [2, 17] },
    { id: 6, nome: "O sistema não deve possuir menus suspensos", metricas: [1, 22] },
    { id: 7, nome: "O sistema não deve restringir tempo das interações", metricas: [3, 18] },
    { id: 8, nome: "O sistema não deve utilizar animações e movimentos rápidos", metricas: [4, 19] },
    { id: 9, nome: "O sistema deve utilizar baixas frequências para prover informações auditivas", metricas: [2, 5] },
    { id: 10, nome: "O sistema deve utilizar tons de confirmação e alertas para prover informações auditivas", metricas: [2, 5] },
    { id: 11, nome: "O sistema deve possuir espaço em branco suficiente para separação de informações", metricas: [6, 15] },
    { id: 12, nome: "O sistema deve oferecer feedback claro, tátil, visuais e/ou sonoras", metricas: [2, 7, 20] },
    { id: 13, nome: "O sistema deve enviar feedback de cada ação do usuário", metricas: [2, 7] },
    { id: 14, nome: "O sistema deve usar linguagem simples, compreensível e apropriada para o público idoso", metricas: [6, 8] },
    { id: 15, nome: "O sistema deve possuir elementos da página fáceis de ler", metricas: [6, 8] },
    { id: 16, nome: "O sistema deve especificar o nome e o estado da tarefa durante a sua execução", metricas: [6, 8] },
    { id: 17, nome: "O sistema deve oferecer instruções claras e específicas", metricas: [7, 6] },
    { id: 18, nome: "O sistema deve tornar a ajuda e documentação acessível", metricas: [9, 21] },
    { id: 19, nome: "O sistema deve tornar a informação simples e fácil de seguir as instruções caso informe um erro", metricas: [10, 21] },
    { id: 20, nome: "O sistema deve utilizar palavras e verbos corretos na orientação para a ação", metricas: [7, 10] },
    { id: 21, nome: "O sistema deve possuir nomes das funções e/ou comandos simples, fáceis de identificar e sem dupla interpretação", metricas: [6, 8] },
    { id: 22, nome: "O sistema deve apresentar hierarquia das informações, ou seja, informações importantes aparecem no topo da tela", metricas: [22, 29] },
    { id: 23, nome: "O sistema não deve utilizar abreviatura, jargões técnicos e palavras estrangeiras", metricas: [6, 8] },
    { id: 24, nome: "O sistema  deve possuir funções que reduzem a carga de memória do idoso", metricas: [6, 23] },
    { id: 25, nome: "O sistema deve focar em uma única tarefa", metricas: [11, 23] },
    { id: 26, nome: "O sistema deve possuir funções apropriadas ao ambiente e às necessidades dos usuários", metricas: [6, 11] },
    { id: 27, nome: "O sistema deve permitir ao usuário ajustar o tamanho de texto e ícones", metricas: [6, 24] },
    { id: 28, nome: "O sistema deve permitir ao usuário alterar o contraste", metricas: [6, 24] },
    { id: 29, nome: "O sistema deve permitir a usuário configurar áudios e conteúdos que possuem movimento", metricas: [6, 24] },
    { id: 30, nome: "O sistema deve respeitar as limitações físicas da tela e perspectiva do usuário", metricas: [11, 15] },
    { id: 31, nome: "O sistema deve possuir mínimo de telas possíveis", metricas: [6, 25] },
    { id: 32, nome: "O sistema deve apresentar botão de voltar em toda as páginas", metricas: [1, 26] },
    { id: 33, nome: "O sistema deve esconder componentes inativos na interface", metricas: [6, 12] },
    { id: 34, nome: "O sistema deve prevenir a ocorrência de erros", metricas: [3, 6] },
    { id: 35, nome: "O sistema deve optar por seleção de opções para entrada de dados", metricas: [12, 6] },
    { id: 36, nome: "O sistema deve apresentar rótulos e/ou instruções nas entradas de dados", metricas: [10, 20, 27] },
    { id: 37, nome: "O sistema deve apresentar detecção automática de erros e mensagem durante a entrada de dados pelo usuário", metricas: [7, 10] },
    { id: 38, nome: "O sistema deve permitir ao usuário verificar e corrigir informação submetidas", metricas: [13, 28, 30] },
    { id: 39, nome: "O sistema não deve apresentar textos truncados", metricas: [10, 14] },
    { id: 40, nome: "O sistema deve criar interface harmoniosa com imagens e gráficos adequados", metricas: [10, 15] },
    { id: 41, nome: "O sistema não deve utilizar a cor branca pura ou alternância rápida de fundo", metricas: [15, 19] },
    { id: 42, nome: "O sistema não deve  usar de azul verde e amarelo em áreas próximas", metricas: [15, 19] },
    { id: 43, nome: "O sistema deve utilizar combinações de alto contraste de cor em fontes e gráficos e o fundo da tela", metricas: [15, 19] },
    { id: 44, nome: "O sistema deve usar as cores de forma conservadora, limitando o número de cores em quatro", metricas: [15, 19] },
    { id: 45, nome: "O sistema deve utilizar  ícones simples, conhecidos e fácil de associar para os idosos", metricas: [10, 19] },
    { id: 46, nome: "O sistema deve apresentar botões e links grande", metricas: [14, 6] },
    { id: 47, nome: "O sistema deve apresentar fontes legíveis não serifadas, não condensadas, não itálicas", metricas: [14, 6] },
    { id: 48, nome: "O sistema deve apresentar fontes alinhadas à esquerda", metricas: [14, 6] },
    { id: 49, nome: "O sistema deve apresentar fontes de tamanho entre 12 e 14", metricas: [14, 6] },
    { id: 50, nome: "O sistema deve apresentar opções de configuração de adaptabilidade e acessibilidade, ao iniciar a aplicação pela primeira vez", metricas: [6, 24] },
    { id: 51, nome: "O sistema deve permitir modificar ou reiniciar as opções de  configuração de adaptabilidade e acessibilidade", metricas: [6, 24] },
    { id: 52, nome: "O sistema deve salvar as configurações ou as ações realizadas pelo usuário", metricas: [3, 6] },
  ]
}

module.exports = list;